on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

name: PR Preview

# Permissions needed to push the preview to gh-pages and comment on the PR
permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        if: github.event.action != 'closed'
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto Project
        if: github.event.action != 'closed'
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: website

      - name: Deploy PR preview
        id: preview-step
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _output
          action: ${{ github.event.action == 'closed' && 'remove' || 'deploy' }}
          comment: "false"
          wait-for-pages-deployment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'deploy' && env.deployment_status == 'success'
        with:
          header: pr-preview
          recreate: true
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            | :rocket: View preview at <br> ${{ steps.preview-step.outputs.preview-url }} <br><br>
            | <h6>Built to branch [`gh-pages`](${{ github.server_url }}/${{ github.repository }}/tree/gh-pages) at ${{ steps.preview-step.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'remove' && env.deployment_status == 'success'
        with:
          header: pr-preview
          recreate: true
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.preview-step.outputs.action-start-time }}
